server:
  port: 8083


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: admin
    url: jdbc:mysql://localhost:3306/studentdb
    username: root

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
